// <auto-generated />
namespace ResourceMetadata.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addTransmissionToAdverts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTransmissionToAdverts));
        
        string IMigrationMetadata.Id
        {
            get { return "201512311120456_addTransmissionToAdverts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
