// <auto-generated />
namespace ResourceMetadata.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class add_type_to_Adverts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_type_to_Adverts));
        
        string IMigrationMetadata.Id
        {
            get { return "201505241522558_add_type_to_Adverts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
