source 'https://rubygems.org'

gem 'rails', '3.2.1'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'execjs'
gem 'devise'
gem 'cancan'
gem 'thumbs_up'
gem 'rack-cache', :require => 'rack/cache'
gem 'dragonfly', '~>0.9.12'
gem 'carrierwave'
gem 'mini_magick'
gem 'acts-as-taggable-on', '~> 2.3.1'
gem 'will_paginate'
gem 'ckeditor'
gem 'sunspot_rails' #форк для rails
gem 'sunspot_solr'  #сам Solr
gem 'progress_bar'
gem 'jquery-cookie-rails'
group :development do
  gem 'annotate'
  gem 'pry'
  gem 'rspec-rails'
end
# Gems used only for assets and not required
# in production environments by default.
group :test do
  gem 'rspec-rails'
  gem 'webrat'
end
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'therubyracer', :platforms => :ruby
  gem 'uglifier', '>= 1.0.3'
  gem 'bootstrap-sass', '~> 2.2.2.0'
  gem 'jquery-ui-rails'
end

gem 'jquery-rails'

